### PR TITLE
Ouch - a prototype CouchDB/PouchDB driver for Go/GopherJS

### PR DESCRIPTION
**Pull request by elliott5**
@dennwc - This PR is to let you know that I'm making some progress with the driver we discussed at https://discourse.cayley.io/t/running-cayley-in-the-browser/960/14

Go/CouchDB runs nosqltest.TestAll() with 8 reported errors (see below).

GopherJS/PouchDB (both locally and remoting to CouchDB) have made less progress, with only a trivial hacked-together TestInsertDelete() passing so far.

I've not set the tests up to use Docker yet, please see README.md for my test setup.

The code is a bit of a mess just now with all my debug guff, and few comments ... but I think there is enough to illustrate what I've been up to over the last week or so.

Obviously happy to have feedback if you (or anyone else) feels moved to give it.

Also hope that this PR thread will allow me to ask questions when I need to.

```
Elliotts-MacBook-Pro15:ouch elliott$ go test
2017/12/02 18:02:27 ERROR: Error: Couldn't retrieve node 84b4ece65dc68422fd694583630ab8b87bc179a9 not found
2017/12/02 18:02:27 ERROR: Error: Couldn't retrieve node 84b4ece65dc68422fd694583630ab8b87bc179a9 not found
--- FAIL: TestOuchAll (11.78s)
        ouch_test.go:208: Testing against: http://testusername:testpassword@127.0.0.1:5984/ouchtest
    --- FAIL: TestOuchAll/qs (8.78s)
        --- FAIL: TestOuchAll/qs/horizon_int (0.94s)
        Error Trace:    graphtest.go:264
        Error:          Not equal:
                        expected: 11
                        actual: 0
        Messages:       Unexpected horizon value
        --- FAIL: TestOuchAll/qs/iterator (1.01s)
        Error Trace:    graphtest.go:328
        Error:          Not equal:
                        expected: []string{"A", "B", "C", "D", "E", "F", "G", "cool", "follows", "status", "status_graph"}
                        actual: []string{"", "", "", "", "", "", "", "", "", "", ""}

                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,13 +1,13 @@
                         ([]string) (len=11) {
                        - (string) (len=1) "A",
                        - (string) (len=1) "B",
                        - (string) (len=1) "C",
                        - (string) (len=1) "D",
                        - (string) (len=1) "E",
                        - (string) (len=1) "F",
                        - (string) (len=1) "G",
                        - (string) (len=4) "cool",
                        - (string) (len=7) "follows",
                        - (string) (len=6) "status",
                        - (string) (len=12) "status_graph"
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) ""
                         }
        Messages:       Unexpected iterated result on repeat 0
        --- FAIL: TestOuchAll/qs/hasa (0.96s)
        Error Trace:    graphtest.go:162
                        graphtest.go:392
        Error:          Not equal:
                        expected: 11
                        actual: 0
        Messages:       [follows follows follows follows follows follows follows follows status status status]
                        vs
                        []
        --- FAIL: TestOuchAll/qs/load_typed_quad (0.81s)
        Error Trace:    graphtest.go:594
        Error:          Should be true
        Messages:       Failed to roundtrip "\"2017-12-02T18:02:20Z\"^^<schema:DateTime>" (quad.Time), got "\"2017-12-02T18:02:20Z\"^^<schema:DateTime>" (quad.Time)
        --- FAIL: TestOuchAll/qs/add_and_remove (0.93s)
        Error Trace:    graphtest.go:155
                        graphtest.go:648
        Error:          Not equal:
                        expected: []string{"A", "B", "C", "D", "E", "F", "G", "cool", "follows", "status", "status_graph"}
                        actual: []string{"", "", "", "", "", "", "", "", "", "", ""}

                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,13 +1,13 @@
                         ([]string) (len=11) {
                        - (string) (len=1) "A",
                        - (string) (len=1) "B",
                        - (string) (len=1) "C",
                        - (string) (len=1) "D",
                        - (string) (len=1) "E",
                        - (string) (len=1) "F",
                        - (string) (len=1) "G",
                        - (string) (len=4) "cool",
                        - (string) (len=7) "follows",
                        - (string) (len=6) "status",
                        - (string) (len=12) "status_graph"
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) "",
                        + (string) ""
                         }
        --- FAIL: TestOuchAll/qs/compare_typed_values (0.90s)
        Error Trace:    graphtest.go:162
                        graphtest.go:848
        Error:          Not equal:
                        expected: 1
                        actual: 0
        Messages:       [_:alice]
                        vs
                        []
    --- FAIL: TestOuchAll/paths (2.98s)
        --- FAIL: TestOuchAll/paths/implicit_All (0.00s)
                pathtest.go:422: got: [](0) expected: ["cool_person" "smart_person" <alice> <are> <bob> <charlie> <dani> <emily> <follows> <fred> <greg> <predicates> <smart_graph> <status>](14)
        --- FAIL: TestOuchAll/paths/implicit_All_(unoptimized) (0.00s)
                pathtest.go:422: got: [](0) expected: ["cool_person" "smart_person" <alice> <are> <bob> <charlie> <dani> <emily> <follows> <fred> <greg> <predicates> <smart_graph> <status>](14)
FAIL
```

---
This change is [Reviewable](https://reviewable.io/reviews/dennwc/cayley/3)

### CODE REVIEW

**Comment by dennwc** [comment]
Great name for the backend :D

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[graph/nosql/ouch/debug.go, line 21 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-Oa8oyekvy1gFSbAeO:-L-Oa8oyekvy1gFSbAeP:bdbqv8g) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/debug.go#L21)):*
> ```Go
> }
> 
> func dcompare(decoded, d nosql.Document) error {
> ```

you can use `require.Equal` (it prints diff) for tests and `reflect.DeepEqual` + `fmt.Sprintf("%#v")` for the package

---

*[graph/nosql/ouch/ouch.go, line 68 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OQmdchLGAJrzbC-EC:-L-OQmdchLGAJrzbC-ED:b-hlkclk) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L68)):*
> ```Go
> 	dsn := strings.TrimSuffix(addr, dbName)
> 
> 	client, err := kivik.New(context.TODO(), driver, dsn)
> ```

`ctx := context.TODO()` at the top of the function

---

*[graph/nosql/ouch/ouch.go, line 259 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-ORbDSLOKqcKU4H8XN:-L-ORbDSLOKqcKU4H8XO:bufrilk) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L259)):*
> ```Go
> 			test = "$lte"
> 		default:
> 			panic("unknown nosqlFilter " + string(rune(filter.Filter)+'0'))
> ```

it's better to print it with `%v`, it should return something reasonable

---

*[graph/nosql/ouch/ouch.go, line 284 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-ORwBnWwTD-WBnqXLv:-L-ORwBnWwTD-WBnqXLw:b-w1e41o) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L284)):*
> ```Go
> func (q *Query) Count(ctx context.Context) (int64, error) {
> 	dpanic("Query.Count")
> 	it := q.Iterate()
> ```

I guess nosql should allow to return `ErrNotImplemented` from here and do this loop on its end. Might be also useful for Filter implementation - while backend is not fully functional we can let filters to scan the entire dataset and filter values on Go side.

---

*[graph/nosql/ouch/ouch.go, line 342 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OS_29LcvG3gUYwg8o:-L-OS_29LcvG3gUYwg8p:b-nezl8j) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L342)):*
> ```Go
> func (it *Iterator) Err() error {
> 	dpanic("Iterator.Err")
> 	return it.err
> ```

kivik returns no errors?

---

*[graph/nosql/ouch/ouch.go, line 351 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OSr_FJcZH1v1O_wJx:-L-OSr_FJcZH1v1O_wJy:b6s5s05) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L351)):*
> ```Go
> 	dpanic("Iterator.Key")
> 	id := it.rows.ID()
> 	if len(id) == 0 {
> ```

How can it happen? Is it something different from `_id` field below?

---

*[graph/nosql/ouch/ouch.go, line 352 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OTSAHn1Kl7AGd8Zpf:-L-OTSAHn1Kl7AGd8Zpg:b-js0773) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L352)):*
> ```Go
> 	id := it.rows.ID()
> 	if len(id) == 0 {
> 		err1 := errors.New("Iterator.Key empty ouch id")
> ```

global `var errEmptyID = ...`

---

*[graph/nosql/ouch/ouch.go, line 354 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OT3k3PJCpVeOMyrYm:-L-OT3k3PJCpVeOMyrYn:b-ycyin4) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L354)):*
> ```Go
> 		err1 := errors.New("Iterator.Key empty ouch id")
> 		doc := map[string]interface{}{}
> 		err2 := it.rows.ScanDoc(&doc)
> ```

Is it possible to Scan twice?

---

*[graph/nosql/ouch/ouch.go, line 359 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OTK1V4P6c31ia36dZ:-L-OTK1V4P6c31ia36d_:bs7kiyx) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L359)):*
> ```Go
> 			it.err = err1
> 			fmt.Println("DEBUG", it.err)
> 			return nosql.Key{}
> ```

It should return nil, same below

---

*[graph/nosql/ouch/ouch.go, line 409 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OTwCsWW7fnAeb-03l:-L-OTwCsWW7fnAeb-03m:b59bvjk) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L409)):*
> ```Go
> 	dpanic("Delete.Do")
> 
> 	d.q.(*Query).ouchQuery["selector"].(map[string]interface{})[idField] = map[string]interface{}{"$in": d.keys}
> ```

Only if `keys` are present?

---

*[graph/nosql/ouch/ouch.go, line 409 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OU4oJC0sOTyRvowP8:-L-OU4oJC0sOTyRvowP9:bhy8mf8) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L409)):*
> ```Go
> 	dpanic("Delete.Do")
> 
> 	d.q.(*Query).ouchQuery["selector"].(map[string]interface{})[idField] = map[string]interface{}{"$in": d.keys}
> ```

If it's necessary, `d.q` may have type `*Query` instead of `nosql.Query`

---

*[graph/nosql/ouch/ouch.go, line 456 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OUZgZ1UzGeGUgxtiZ:-L-OUZgZ1UzGeGUgxti_:b715f0r) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L456)):*
> ```Go
> }
> 
> func (u *Update) Push(field string, v nosql.Value) nosql.Update {
> ```

I think I dropped Push from API some time ago

---

*[graph/nosql/ouch/ouch_test.go, line 88 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-O_Q3rsc6C6PxTsBDr:-L-O_Q3rsc6C6PxTsBDs:bfhol1t) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch_test.go#L88)):*
> ```Go
> 
> // TestInsertDelete does very basic testing
> func TestInsertDelete(t *testing.T) {
> ```

I guess most of these tests can be move to `nosqltest` package - it will be easier to verify compatibility between backends even before running graph tests.

Would you mind to split this change into separate PR, and verify these tests on Mongo? After merging it `TestOuchAll` will automatically run these tests.

---

*[graph/nosql/ouch/values.go, line 60 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OP5xjkXO5zV2VQi7k:-L-OP5xkDeiMUWFC8bD9:b-9h94x2) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/values.go#L60)):*
> ```Go
> 		return "S" + string(v) // need leading "S"
> 	case nosql.Int: // special handling here, as type can't be inferred from json
> 		return "I" + itos(int64(v))
> ```

There is an interesting fix for this situation. Decoder can be told to decode to `json.Number` that can be checked for int/float later (int first). 

So we can check if saved value is int or float. But what about "0"? Is it int or float? The fix is simple - always encode floats into `json.Raw(fmt.Sprintf("%e", v))`, meaning that even "0" float will be in exponential notation and can be distinguished from "0" of int.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dennwc/cayley/3#-:-L-OUzfzBm1NvgeT83H7:bv1bpo9)*

**Comment by dennwc** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[graph/nosql/ouch/ouch_test.go, line 88 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-O_Q3rsc6C6PxTsBDr:-L-QxPw0um2X8EZKLQHt:b-wu028v) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch_test.go#L88)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

I guess most of these tests can be move to `nosqltest` package - it will be easier to verify compatibility between backends even before running graph tests.

Would you mind to split this change into separate PR, and verify these tests on Mongo? After merging it `TestOuchAll` will automatically run these tests.
</blockquote></details>

But let my fix Mongo first :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dennwc/cayley/3)*

**Comment by elliott5** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[graph/nosql/ouch/debug.go, line 21 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-Oa8oyekvy1gFSbAeO:-L-QAAB6sXFuH6UZoe1n:b-yezwp2) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/debug.go#L21)):*
> you can use require.Equal (it prints diff) for tests and reflect.DeepEqual + fmt.Sprintf("%#v") for the package
I had problems with reflect.DeepEqual() and nosql.Document earlier in the project and (to my shame) I've not used require.Equal() before.
You are right that they would be a more rigorous approach than I have now, so I'll look to change it.

---

*[graph/nosql/ouch/ouch.go, line 68 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OQmdchLGAJrzbC-EC:-L-WdUl4Yb8triTKozO-:b32w0x) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L68)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

`ctx := context.TODO()` at the top of the function
</blockquote></details>

OK

---

*[graph/nosql/ouch/ouch.go, line 259 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-ORbDSLOKqcKU4H8XN:-L-WdXN8YaNPAPDskUDf:b32w0x) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L259)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

it's better to print it with `%v`, it should return something reasonable
</blockquote></details>

OK

---

*[graph/nosql/ouch/ouch.go, line 284 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-ORwBnWwTD-WBnqXLv:-L-WdcfMrx20K03dCNwb:boc4veq) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L284)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

I guess nosql should allow to return `ErrNotImplemented` from here and do this loop on its end. Might be also useful for Filter implementation - while backend is not fully functional we can let filters to scan the entire dataset and filter values on Go side.
</blockquote></details>

We may need that, but first I need to see if there is a "count" function in the interface I may have missed.

---

*[graph/nosql/ouch/ouch.go, line 342 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OS_29LcvG3gUYwg8o:-L-QYK5sBjtesO2hekeq:b-fy6yct) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L342)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

kivik returns no errors?
</blockquote></details>

Good spot, I'll change it to catch errors properly.

---

*[graph/nosql/ouch/ouch.go, line 351 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OSr_FJcZH1v1O_wJx:-L-WbfAKuoENU9E1H8Ew:b2cy55f) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L351)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

How can it happen? Is it something different from `_id` field below?
</blockquote></details>

This is some internal condition within kivik, possibly to do with locking, that I've yet to get to grips with.

---

*[graph/nosql/ouch/ouch.go, line 352 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OTSAHn1Kl7AGd8Zpf:-L-WbwMYHCnLNukmI8JG:b-vbq5ck) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L352)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

global `var errEmptyID = ...`
</blockquote></details>

yes, if necessary...

---

*[graph/nosql/ouch/ouch.go, line 354 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OT3k3PJCpVeOMyrYm:-L-WbzfQM-BAtQ5iTFgJ:brmnzu) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L354)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Is it possible to Scan twice?
</blockquote></details>

Seems so, but the second scan is because of an error condition, so hopefully it will be removed.

---

*[graph/nosql/ouch/ouch.go, line 359 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OTK1V4P6c31ia36dZ:-L-WccFYP-UqDKyFGum7:b32w0x) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L359)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

It should return nil, same below
</blockquote></details>

OK

---

*[graph/nosql/ouch/ouch.go, line 409 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OTwCsWW7fnAeb-03l:-L-WcsXeyl7WzAD4G_R2:b-mx3x4z) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L409)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Only if `keys` are present?
</blockquote></details>

Well spotted!

---

*[graph/nosql/ouch/ouch.go, line 409 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OU4oJC0sOTyRvowP8:-L-WcvMBRN7YCqgwaKxa:b32w0x) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L409)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

If it's necessary, `d.q` may have type `*Query` instead of `nosql.Query`
</blockquote></details>

OK

---

*[graph/nosql/ouch/ouch.go, line 456 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OUZgZ1UzGeGUgxtiZ:-L-WdEHCpH2QSnq3S3cE:b32w0x) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch.go#L456)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

I think I dropped Push from API some time ago
</blockquote></details>

OK

---

*[graph/nosql/ouch/ouch_test.go, line 88 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-O_Q3rsc6C6PxTsBDr:-L-WaabltRM1QM_JRHUx:bkxrxqx) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch_test.go#L88)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

But let my fix Mongo first :)
</blockquote></details>

I'm not sure my trivial tests are worth adding to be honest, once the thing is working they can be deleted.

---

*[graph/nosql/ouch/values.go, line 60 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OP5xjkXO5zV2VQi7k:-L-WanVdVwMfEl38lhPn:b-nh8jkb) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/values.go#L60)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

There is an interesting fix for this situation. Decoder can be told to decode to `json.Number` that can be checked for int/float later (int first). 

So we can check if saved value is int or float. But what about "0"? Is it int or float? The fix is simple - always encode floats into `json.Raw(fmt.Sprintf("%e", v))`, meaning that even "0" float will be in exponential notation and can be distinguished from "0" of int.
</blockquote></details>

The difficulty is that int64 can't be represented in JS/JSON as all numbers are float64 (which int64 will not fit within), hence this approach of serialising int64 into a sortable string.

Once it is all working, we can think about optimization.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dennwc/cayley/3)*

**Comment by elliott5** [comment]
I'm trying to digest your changes to your dennwc:nosql-indexes branch too...

**Comment by dennwc** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[graph/nosql/ouch/ouch_test.go, line 88 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-O_Q3rsc6C6PxTsBDr:-L-WfgAXXprgoldU8GmL:bim065) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/ouch_test.go#L88)):*
<details><summary><i>Previously, elliott5 (Elliott Stoneham) wrote…</i></summary><blockquote>

I'm not sure my trivial tests are worth adding to be honest, once the thing is working they can be deleted.
</blockquote></details>

Even trivial tests are better than having to debug backend thru QuadStore :) It will catch subtle problems earlier. I added Insert-Find-Iterate and Insert-Delete tests to the branch (and fixed current backends), so feel free to add/port more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dennwc/cayley/3)*

**Comment by dennwc** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[graph/nosql/ouch/values.go, line 60 at r1](https://reviewable.io:443/reviews/dennwc/cayley/3#-L-OP5xjkXO5zV2VQi7k:-L-WhS5h4S3y5OWs3eSF:b78x80f) ([raw file](https://github.com/dennwc/cayley/blob/7dec7250318ca03447a7e9f20d472f2a33ad49fa/graph/nosql/ouch/values.go#L60)):*
<details><summary><i>Previously, elliott5 (Elliott Stoneham) wrote…</i></summary><blockquote>

The difficulty is that int64 can't be represented in JS/JSON as all numbers are float64 (which int64 will not fit within), hence this approach of serialising int64 into a sortable string.

Once it is all working, we can think about optimization.
</blockquote></details>

I'm also thinking about another approach to this - just save int/float in fields with different names. It turned out that ElasticSearch can't change the type of the field once it's written, thus we will be forced to create distinct fields for each type. Same problem exists with Dynamo - although it can store exp notation, it will still parse the value and will not preserve the notation.

So let's leave it as-is now, I'll fix it on `nosql` level. As a bonus, it will be possible to store value directly and let `nosql` layer to convert it according to expected type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dennwc/cayley/3)*

**Comment by elliott5** [comment]
Just want to say thank you for writing  nosqltest.TestNoSQL() very helpful to get the basics right.

Down to 3 bugs on the go/CouchDB side now, so hopefully a working (if fragile & un-optimized) driver for that target is not too far off.

**Comment by elliott5** [comment]
Now have all tests passing on go/CouchDB! ...working on GopherJS/PouchDB.

**Comment by dennwc** [comment]
Great! I will try to push few more tests for Update today or tomorrow.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dennwc/cayley/3#-:-L-cMQ0N8OAd-vDBQANN:b-di0qsh)*

**Comment by dennwc** [comment]
Hmm, sorry, this was not intentional. I moved all changes to `nosql` branch and removed temporary `nosql-indexes` branch. Feel free to re-submit PR on top of that branch (it's only one commit ahead).

I added few tests for Update. They are not yet complete, but would cover few most typical cases. Already fixed few bugs in Mongo and Dynamo with these tests :)

**Pull request closed without merging**
